### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by BA7JCM** [zww7821270/gdgbpx_auto#6]
能成功登录，但是登录之后就没动静了，回到编辑器里面看发现报错下面的内容

Traceback (most recent call last):
  File "D:/Downloads/gdgbpx_auto-main/gdgbpx_auto.py", line 143, in <module>
    main()
  File "D:/Downloads/gdgbpx_auto-main/gdgbpx_auto.py", line 122, in main
    elems[0].click();
IndexError: list index out of range

**Comment by zww7821270** [comment]
根据我刚刚进去网站查看，网页已经改版，自动看视频代码已经不能使用。

**Comment by LevineWoo** [comment]
> 根据我刚刚进去网站查看，网页已经改版，自动看视频代码已经不能使用。

大佬是为了规避风险嘛？哈哈

简单注释几行就可以用了。感谢大佬

**Comment by zww7821270** [comment]
> > 根据我刚刚进去网站查看，网页已经改版，自动看视频代码已经不能使用。
> 
> 大佬是为了规避风险嘛？哈哈
> 
> 简单注释几行就可以用了。感谢大佬

收到很多邮件说代码无法使用问题，没办法一一回复，核实后确实看到网站改版，所以改了readme和回复了这个兄弟

**Comment by ShunLiu1992** [comment]
大佬，我登录进去后报错

Traceback (most recent call last):
  File "gdgbpx_auto.py", line 165, in <module>
    main()
  File "gdgbpx_auto.py", line 142, in main
    elem.click()
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 81, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 710, in _execute
    return self._parent.execute(command, params)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 424, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a id="btnStudy" href="javascript:__doPostBack('btnStudy','')">...</a> is not clickable at point (967, 698). Other element would receive the click: <div class="layui-layer-shade" id="layui-layer-shade1" times="1" style="z-index:19891014; background-color:#000; opacity:0.3; filter:alpha(opacity=30);"></div>
  (Session info: chrome=96.0.4664.110)
Stacktrace:
0   chromedriver                        0x0000000109dba269 __gxx_personality_v0 + 582729
1   chromedriver                        0x0000000109d45c33 __gxx_personality_v0 + 106003
2   chromedriver                        0x0000000109902e28 chromedriver + 171560
3   chromedriver                        0x000000010993f681 chromedriver + 419457
4   chromedriver                        0x000000010993d33e chromedriver + 410430
5   chromedriver                        0x000000010993ab5a chromedriver + 400218
6   chromedriver                        0x00000001099395f1 chromedriver + 394737
7   chromedriver                        0x000000010992d659 chromedriver + 345689
8   chromedriver                        0x0000000109955962 chromedriver + 510306
9   chromedriver                        0x000000010992cf45 chromedriver + 343877
10  chromedriver                        0x0000000109955c7e chromedriver + 511102
11  chromedriver                        0x0000000109968462 chromedriver + 586850
12  chromedriver                        0x0000000109955c23 chromedriver + 511011
13  chromedriver                        0x000000010992b75e chromedriver + 337758
14  chromedriver                        0x000000010992ca95 chromedriver + 342677
15  chromedriver                        0x0000000109d768ab __gxx_personality_v0 + 305803
16  chromedriver                        0x0000000109d8d863 __gxx_personality_v0 + 399939
17  chromedriver                        0x0000000109d92c7f __gxx_personality_v0 + 421471
18  chromedriver                        0x0000000109d8ebba __gxx_personality_v0 + 404890
19  chromedriver                        0x0000000109d6ae51 __gxx_personality_v0 + 258097
20  chromedriver                        0x0000000109daa158 __gxx_personality_v0 + 516920
21  chromedriver                        0x0000000109daa2e1 __gxx_personality_v0 + 517313
22  chromedriver                        0x0000000109dc16f8 __gxx_personality_v0 + 612568
23  libsystem_pthread.dylib             0x00007fff5f4cf661 _pthread_body + 340
24  libsystem_pthread.dylib             0x00007fff5f4cf50d _pthread_body + 0
25  libsystem_pthread.dylib             0x00007fff5f4cebf9 thread_start + 13

请问如何解决？
